//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class ADLX {
  public static int adlx_atomic_inc(SWIGTYPE_p_long x) {
    int ret = ADLXPINVOKE.adlx_atomic_inc(SWIGTYPE_p_long.getCPtr(x));
    return ret;
  }

  public static int adlx_atomic_dec(SWIGTYPE_p_long x) {
    int ret = ADLXPINVOKE.adlx_atomic_dec(SWIGTYPE_p_long.getCPtr(x));
    return ret;
  }

  public static SWIGTYPE_p_void adlx_load_library(SWIGTYPE_p_wchar_t filename) {
    global::System.IntPtr cPtr = ADLXPINVOKE.adlx_load_library(SWIGTYPE_p_wchar_t.getCPtr(filename));
    SWIGTYPE_p_void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
    return ret;
  }

  public static int adlx_free_library(SWIGTYPE_p_void module) {
    int ret = ADLXPINVOKE.adlx_free_library(SWIGTYPE_p_void.getCPtr(module));
    return ret;
  }

  public static SWIGTYPE_p_void adlx_get_proc_address(SWIGTYPE_p_void module, string procName) {
    global::System.IntPtr cPtr = ADLXPINVOKE.adlx_get_proc_address(SWIGTYPE_p_void.getCPtr(module), procName);
    SWIGTYPE_p_void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
    return ret;
  }

  public static ADLXHelper g_ADLX {
    set {
      ADLXPINVOKE.g_ADLX_set(ADLXHelper.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ADLXPINVOKE.g_ADLX_get();
      ADLXHelper ret = (cPtr == global::System.IntPtr.Zero) ? null : new ADLXHelper(cPtr, false);
      return ret;
    } 
  }

  public static SWIGTYPE_p_ADLX_DISPLAY_TYPE new_displayTypeP() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_displayTypeP();
    SWIGTYPE_p_ADLX_DISPLAY_TYPE ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_ADLX_DISPLAY_TYPE(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_ADLX_DISPLAY_TYPE copy_displayTypeP(ADLX_DISPLAY_TYPE value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_displayTypeP((int)value);
    SWIGTYPE_p_ADLX_DISPLAY_TYPE ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_ADLX_DISPLAY_TYPE(cPtr, false);
    return ret;
  }

  public static void delete_displayTypeP(SWIGTYPE_p_ADLX_DISPLAY_TYPE obj) {
    ADLXPINVOKE.delete_displayTypeP(SWIGTYPE_p_ADLX_DISPLAY_TYPE.getCPtr(obj));
  }

  public static void displayTypeP_assign(SWIGTYPE_p_ADLX_DISPLAY_TYPE obj, ADLX_DISPLAY_TYPE value) {
    ADLXPINVOKE.displayTypeP_assign(SWIGTYPE_p_ADLX_DISPLAY_TYPE.getCPtr(obj), (int)value);
  }

  public static ADLX_DISPLAY_TYPE displayTypeP_value(SWIGTYPE_p_ADLX_DISPLAY_TYPE obj) {
    ADLX_DISPLAY_TYPE ret = (ADLX_DISPLAY_TYPE)ADLXPINVOKE.displayTypeP_value(SWIGTYPE_p_ADLX_DISPLAY_TYPE.getCPtr(obj));
    return ret;
  }

  public static SWIGTYPE_p_ADLX_DISPLAY_CONNECTOR_TYPE new_disConnectTypeP() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_disConnectTypeP();
    SWIGTYPE_p_ADLX_DISPLAY_CONNECTOR_TYPE ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_ADLX_DISPLAY_CONNECTOR_TYPE(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_ADLX_DISPLAY_CONNECTOR_TYPE copy_disConnectTypeP(ADLX_DISPLAY_CONNECTOR_TYPE value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_disConnectTypeP((int)value);
    SWIGTYPE_p_ADLX_DISPLAY_CONNECTOR_TYPE ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_ADLX_DISPLAY_CONNECTOR_TYPE(cPtr, false);
    return ret;
  }

  public static void delete_disConnectTypeP(SWIGTYPE_p_ADLX_DISPLAY_CONNECTOR_TYPE obj) {
    ADLXPINVOKE.delete_disConnectTypeP(SWIGTYPE_p_ADLX_DISPLAY_CONNECTOR_TYPE.getCPtr(obj));
  }

  public static void disConnectTypeP_assign(SWIGTYPE_p_ADLX_DISPLAY_CONNECTOR_TYPE obj, ADLX_DISPLAY_CONNECTOR_TYPE value) {
    ADLXPINVOKE.disConnectTypeP_assign(SWIGTYPE_p_ADLX_DISPLAY_CONNECTOR_TYPE.getCPtr(obj), (int)value);
  }

  public static ADLX_DISPLAY_CONNECTOR_TYPE disConnectTypeP_value(SWIGTYPE_p_ADLX_DISPLAY_CONNECTOR_TYPE obj) {
    ADLX_DISPLAY_CONNECTOR_TYPE ret = (ADLX_DISPLAY_CONNECTOR_TYPE)ADLXPINVOKE.disConnectTypeP_value(SWIGTYPE_p_ADLX_DISPLAY_CONNECTOR_TYPE.getCPtr(obj));
    return ret;
  }

  public static SWIGTYPE_p_ADLX_DISPLAY_SCAN_TYPE new_disScanTypeP() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_disScanTypeP();
    SWIGTYPE_p_ADLX_DISPLAY_SCAN_TYPE ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_ADLX_DISPLAY_SCAN_TYPE(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_ADLX_DISPLAY_SCAN_TYPE copy_disScanTypeP(ADLX_DISPLAY_SCAN_TYPE value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_disScanTypeP((int)value);
    SWIGTYPE_p_ADLX_DISPLAY_SCAN_TYPE ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_ADLX_DISPLAY_SCAN_TYPE(cPtr, false);
    return ret;
  }

  public static void delete_disScanTypeP(SWIGTYPE_p_ADLX_DISPLAY_SCAN_TYPE obj) {
    ADLXPINVOKE.delete_disScanTypeP(SWIGTYPE_p_ADLX_DISPLAY_SCAN_TYPE.getCPtr(obj));
  }

  public static void disScanTypeP_assign(SWIGTYPE_p_ADLX_DISPLAY_SCAN_TYPE obj, ADLX_DISPLAY_SCAN_TYPE value) {
    ADLXPINVOKE.disScanTypeP_assign(SWIGTYPE_p_ADLX_DISPLAY_SCAN_TYPE.getCPtr(obj), (int)value);
  }

  public static ADLX_DISPLAY_SCAN_TYPE disScanTypeP_value(SWIGTYPE_p_ADLX_DISPLAY_SCAN_TYPE obj) {
    ADLX_DISPLAY_SCAN_TYPE ret = (ADLX_DISPLAY_SCAN_TYPE)ADLXPINVOKE.disScanTypeP_value(SWIGTYPE_p_ADLX_DISPLAY_SCAN_TYPE.getCPtr(obj));
    return ret;
  }

  public static SWIGTYPE_p_size_t new_adlx_sizeP() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_adlx_sizeP();
    SWIGTYPE_p_size_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_size_t(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_size_t copy_adlx_sizeP(uint value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_adlx_sizeP(value);
    SWIGTYPE_p_size_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_size_t(cPtr, false);
    return ret;
  }

  public static void delete_adlx_sizeP(SWIGTYPE_p_size_t obj) {
    ADLXPINVOKE.delete_adlx_sizeP(SWIGTYPE_p_size_t.getCPtr(obj));
  }

  public static void adlx_sizeP_assign(SWIGTYPE_p_size_t obj, uint value) {
    ADLXPINVOKE.adlx_sizeP_assign(SWIGTYPE_p_size_t.getCPtr(obj), value);
  }

  public static uint adlx_sizeP_value(SWIGTYPE_p_size_t obj) {
    uint ret = ADLXPINVOKE.adlx_sizeP_value(SWIGTYPE_p_size_t.getCPtr(obj));
    return ret;
  }

  public static ADLX_IntRange new_adlx_intRangeP() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_adlx_intRangeP();
    ADLX_IntRange ret = (cPtr == global::System.IntPtr.Zero) ? null : new ADLX_IntRange(cPtr, false);
    return ret;
  }

  public static ADLX_IntRange copy_adlx_intRangeP(ADLX_IntRange value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_adlx_intRangeP(ADLX_IntRange.getCPtr(value));
    ADLX_IntRange ret = (cPtr == global::System.IntPtr.Zero) ? null : new ADLX_IntRange(cPtr, false);
    if (ADLXPINVOKE.SWIGPendingException.Pending) throw ADLXPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static void delete_adlx_intRangeP(ADLX_IntRange obj) {
    ADLXPINVOKE.delete_adlx_intRangeP(ADLX_IntRange.getCPtr(obj));
  }

  public static void adlx_intRangeP_assign(ADLX_IntRange obj, ADLX_IntRange value) {
    ADLXPINVOKE.adlx_intRangeP_assign(ADLX_IntRange.getCPtr(obj), ADLX_IntRange.getCPtr(value));
    if (ADLXPINVOKE.SWIGPendingException.Pending) throw ADLXPINVOKE.SWIGPendingException.Retrieve();
  }

  public static ADLX_IntRange adlx_intRangeP_value(ADLX_IntRange obj) {
    ADLX_IntRange ret = new ADLX_IntRange(ADLXPINVOKE.adlx_intRangeP_value(ADLX_IntRange.getCPtr(obj)), true);
    return ret;
  }

  public static SWIGTYPE_p_ADLX_MEMORYTIMING_DESCRIPTION new_memoryTimingDescriptionP() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_memoryTimingDescriptionP();
    SWIGTYPE_p_ADLX_MEMORYTIMING_DESCRIPTION ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_ADLX_MEMORYTIMING_DESCRIPTION(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_ADLX_MEMORYTIMING_DESCRIPTION copy_memoryTimingDescriptionP(ADLX_MEMORYTIMING_DESCRIPTION value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_memoryTimingDescriptionP((int)value);
    SWIGTYPE_p_ADLX_MEMORYTIMING_DESCRIPTION ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_ADLX_MEMORYTIMING_DESCRIPTION(cPtr, false);
    return ret;
  }

  public static void delete_memoryTimingDescriptionP(SWIGTYPE_p_ADLX_MEMORYTIMING_DESCRIPTION obj) {
    ADLXPINVOKE.delete_memoryTimingDescriptionP(SWIGTYPE_p_ADLX_MEMORYTIMING_DESCRIPTION.getCPtr(obj));
  }

  public static void memoryTimingDescriptionP_assign(SWIGTYPE_p_ADLX_MEMORYTIMING_DESCRIPTION obj, ADLX_MEMORYTIMING_DESCRIPTION value) {
    ADLXPINVOKE.memoryTimingDescriptionP_assign(SWIGTYPE_p_ADLX_MEMORYTIMING_DESCRIPTION.getCPtr(obj), (int)value);
  }

  public static ADLX_MEMORYTIMING_DESCRIPTION memoryTimingDescriptionP_value(SWIGTYPE_p_ADLX_MEMORYTIMING_DESCRIPTION obj) {
    ADLX_MEMORYTIMING_DESCRIPTION ret = (ADLX_MEMORYTIMING_DESCRIPTION)ADLXPINVOKE.memoryTimingDescriptionP_value(SWIGTYPE_p_ADLX_MEMORYTIMING_DESCRIPTION.getCPtr(obj));
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXGPUTuningServices new_gpuTuningP_Ptr() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_gpuTuningP_Ptr();
    SWIGTYPE_p_p_adlx__IADLXGPUTuningServices ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXGPUTuningServices(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXGPUTuningServices copy_gpuTuningP_Ptr(IADLXGPUTuningServices value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_gpuTuningP_Ptr(IADLXGPUTuningServices.getCPtr(value));
    SWIGTYPE_p_p_adlx__IADLXGPUTuningServices ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXGPUTuningServices(cPtr, false);
    return ret;
  }

  public static void delete_gpuTuningP_Ptr(SWIGTYPE_p_p_adlx__IADLXGPUTuningServices obj) {
    ADLXPINVOKE.delete_gpuTuningP_Ptr(SWIGTYPE_p_p_adlx__IADLXGPUTuningServices.getCPtr(obj));
  }

  public static void gpuTuningP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXGPUTuningServices obj, IADLXGPUTuningServices value) {
    ADLXPINVOKE.gpuTuningP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXGPUTuningServices.getCPtr(obj), IADLXGPUTuningServices.getCPtr(value));
  }

  public static IADLXGPUTuningServices gpuTuningP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXGPUTuningServices obj) {
    global::System.IntPtr cPtr = ADLXPINVOKE.gpuTuningP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXGPUTuningServices.getCPtr(obj));
    IADLXGPUTuningServices ret = (cPtr == global::System.IntPtr.Zero) ? null : new IADLXGPUTuningServices(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXManualGraphicsTuning1 new_manualGfxTuning1P_Ptr() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_manualGfxTuning1P_Ptr();
    SWIGTYPE_p_p_adlx__IADLXManualGraphicsTuning1 ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXManualGraphicsTuning1(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXManualGraphicsTuning1 copy_manualGfxTuning1P_Ptr(IADLXManualGraphicsTuning1 value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_manualGfxTuning1P_Ptr(IADLXManualGraphicsTuning1.getCPtr(value));
    SWIGTYPE_p_p_adlx__IADLXManualGraphicsTuning1 ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXManualGraphicsTuning1(cPtr, false);
    return ret;
  }

  public static void delete_manualGfxTuning1P_Ptr(SWIGTYPE_p_p_adlx__IADLXManualGraphicsTuning1 obj) {
    ADLXPINVOKE.delete_manualGfxTuning1P_Ptr(SWIGTYPE_p_p_adlx__IADLXManualGraphicsTuning1.getCPtr(obj));
  }

  public static void manualGfxTuning1P_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXManualGraphicsTuning1 obj, IADLXManualGraphicsTuning1 value) {
    ADLXPINVOKE.manualGfxTuning1P_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXManualGraphicsTuning1.getCPtr(obj), IADLXManualGraphicsTuning1.getCPtr(value));
  }

  public static IADLXManualGraphicsTuning1 manualGfxTuning1P_Ptr_value(SWIGTYPE_p_p_adlx__IADLXManualGraphicsTuning1 obj) {
    global::System.IntPtr cPtr = ADLXPINVOKE.manualGfxTuning1P_Ptr_value(SWIGTYPE_p_p_adlx__IADLXManualGraphicsTuning1.getCPtr(obj));
    IADLXManualGraphicsTuning1 ret = (cPtr == global::System.IntPtr.Zero) ? null : new IADLXManualGraphicsTuning1(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXManualGraphicsTuning2 new_manualGfxTuning2P_Ptr() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_manualGfxTuning2P_Ptr();
    SWIGTYPE_p_p_adlx__IADLXManualGraphicsTuning2 ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXManualGraphicsTuning2(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXManualGraphicsTuning2 copy_manualGfxTuning2P_Ptr(IADLXManualGraphicsTuning2 value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_manualGfxTuning2P_Ptr(IADLXManualGraphicsTuning2.getCPtr(value));
    SWIGTYPE_p_p_adlx__IADLXManualGraphicsTuning2 ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXManualGraphicsTuning2(cPtr, false);
    return ret;
  }

  public static void delete_manualGfxTuning2P_Ptr(SWIGTYPE_p_p_adlx__IADLXManualGraphicsTuning2 obj) {
    ADLXPINVOKE.delete_manualGfxTuning2P_Ptr(SWIGTYPE_p_p_adlx__IADLXManualGraphicsTuning2.getCPtr(obj));
  }

  public static void manualGfxTuning2P_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXManualGraphicsTuning2 obj, IADLXManualGraphicsTuning2 value) {
    ADLXPINVOKE.manualGfxTuning2P_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXManualGraphicsTuning2.getCPtr(obj), IADLXManualGraphicsTuning2.getCPtr(value));
  }

  public static IADLXManualGraphicsTuning2 manualGfxTuning2P_Ptr_value(SWIGTYPE_p_p_adlx__IADLXManualGraphicsTuning2 obj) {
    global::System.IntPtr cPtr = ADLXPINVOKE.manualGfxTuning2P_Ptr_value(SWIGTYPE_p_p_adlx__IADLXManualGraphicsTuning2.getCPtr(obj));
    IADLXManualGraphicsTuning2 ret = (cPtr == global::System.IntPtr.Zero) ? null : new IADLXManualGraphicsTuning2(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXManualFanTuning new_manualFanTuningP_Ptr() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_manualFanTuningP_Ptr();
    SWIGTYPE_p_p_adlx__IADLXManualFanTuning ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXManualFanTuning(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXManualFanTuning copy_manualFanTuningP_Ptr(IADLXManualFanTuning value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_manualFanTuningP_Ptr(IADLXManualFanTuning.getCPtr(value));
    SWIGTYPE_p_p_adlx__IADLXManualFanTuning ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXManualFanTuning(cPtr, false);
    return ret;
  }

  public static void delete_manualFanTuningP_Ptr(SWIGTYPE_p_p_adlx__IADLXManualFanTuning obj) {
    ADLXPINVOKE.delete_manualFanTuningP_Ptr(SWIGTYPE_p_p_adlx__IADLXManualFanTuning.getCPtr(obj));
  }

  public static void manualFanTuningP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXManualFanTuning obj, IADLXManualFanTuning value) {
    ADLXPINVOKE.manualFanTuningP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXManualFanTuning.getCPtr(obj), IADLXManualFanTuning.getCPtr(value));
  }

  public static IADLXManualFanTuning manualFanTuningP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXManualFanTuning obj) {
    global::System.IntPtr cPtr = ADLXPINVOKE.manualFanTuningP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXManualFanTuning.getCPtr(obj));
    IADLXManualFanTuning ret = (cPtr == global::System.IntPtr.Zero) ? null : new IADLXManualFanTuning(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXManualVRAMTuning1 new_manualVRAMTuning1P_Ptr() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_manualVRAMTuning1P_Ptr();
    SWIGTYPE_p_p_adlx__IADLXManualVRAMTuning1 ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXManualVRAMTuning1(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXManualVRAMTuning1 copy_manualVRAMTuning1P_Ptr(IADLXManualVRAMTuning1 value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_manualVRAMTuning1P_Ptr(IADLXManualVRAMTuning1.getCPtr(value));
    SWIGTYPE_p_p_adlx__IADLXManualVRAMTuning1 ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXManualVRAMTuning1(cPtr, false);
    return ret;
  }

  public static void delete_manualVRAMTuning1P_Ptr(SWIGTYPE_p_p_adlx__IADLXManualVRAMTuning1 obj) {
    ADLXPINVOKE.delete_manualVRAMTuning1P_Ptr(SWIGTYPE_p_p_adlx__IADLXManualVRAMTuning1.getCPtr(obj));
  }

  public static void manualVRAMTuning1P_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXManualVRAMTuning1 obj, IADLXManualVRAMTuning1 value) {
    ADLXPINVOKE.manualVRAMTuning1P_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXManualVRAMTuning1.getCPtr(obj), IADLXManualVRAMTuning1.getCPtr(value));
  }

  public static IADLXManualVRAMTuning1 manualVRAMTuning1P_Ptr_value(SWIGTYPE_p_p_adlx__IADLXManualVRAMTuning1 obj) {
    global::System.IntPtr cPtr = ADLXPINVOKE.manualVRAMTuning1P_Ptr_value(SWIGTYPE_p_p_adlx__IADLXManualVRAMTuning1.getCPtr(obj));
    IADLXManualVRAMTuning1 ret = (cPtr == global::System.IntPtr.Zero) ? null : new IADLXManualVRAMTuning1(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXManualVRAMTuning2 new_manualVRAMTuning2P_Ptr() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_manualVRAMTuning2P_Ptr();
    SWIGTYPE_p_p_adlx__IADLXManualVRAMTuning2 ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXManualVRAMTuning2(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXManualVRAMTuning2 copy_manualVRAMTuning2P_Ptr(IADLXManualVRAMTuning2 value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_manualVRAMTuning2P_Ptr(IADLXManualVRAMTuning2.getCPtr(value));
    SWIGTYPE_p_p_adlx__IADLXManualVRAMTuning2 ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXManualVRAMTuning2(cPtr, false);
    return ret;
  }

  public static void delete_manualVRAMTuning2P_Ptr(SWIGTYPE_p_p_adlx__IADLXManualVRAMTuning2 obj) {
    ADLXPINVOKE.delete_manualVRAMTuning2P_Ptr(SWIGTYPE_p_p_adlx__IADLXManualVRAMTuning2.getCPtr(obj));
  }

  public static void manualVRAMTuning2P_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXManualVRAMTuning2 obj, IADLXManualVRAMTuning2 value) {
    ADLXPINVOKE.manualVRAMTuning2P_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXManualVRAMTuning2.getCPtr(obj), IADLXManualVRAMTuning2.getCPtr(value));
  }

  public static IADLXManualVRAMTuning2 manualVRAMTuning2P_Ptr_value(SWIGTYPE_p_p_adlx__IADLXManualVRAMTuning2 obj) {
    global::System.IntPtr cPtr = ADLXPINVOKE.manualVRAMTuning2P_Ptr_value(SWIGTYPE_p_p_adlx__IADLXManualVRAMTuning2.getCPtr(obj));
    IADLXManualVRAMTuning2 ret = (cPtr == global::System.IntPtr.Zero) ? null : new IADLXManualVRAMTuning2(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXManualPowerTuning new_manualPowerTuningP_Ptr() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_manualPowerTuningP_Ptr();
    SWIGTYPE_p_p_adlx__IADLXManualPowerTuning ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXManualPowerTuning(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXManualPowerTuning copy_manualPowerTuningP_Ptr(IADLXManualPowerTuning value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_manualPowerTuningP_Ptr(IADLXManualPowerTuning.getCPtr(value));
    SWIGTYPE_p_p_adlx__IADLXManualPowerTuning ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXManualPowerTuning(cPtr, false);
    return ret;
  }

  public static void delete_manualPowerTuningP_Ptr(SWIGTYPE_p_p_adlx__IADLXManualPowerTuning obj) {
    ADLXPINVOKE.delete_manualPowerTuningP_Ptr(SWIGTYPE_p_p_adlx__IADLXManualPowerTuning.getCPtr(obj));
  }

  public static void manualPowerTuningP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXManualPowerTuning obj, IADLXManualPowerTuning value) {
    ADLXPINVOKE.manualPowerTuningP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXManualPowerTuning.getCPtr(obj), IADLXManualPowerTuning.getCPtr(value));
  }

  public static IADLXManualPowerTuning manualPowerTuningP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXManualPowerTuning obj) {
    global::System.IntPtr cPtr = ADLXPINVOKE.manualPowerTuningP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXManualPowerTuning.getCPtr(obj));
    IADLXManualPowerTuning ret = (cPtr == global::System.IntPtr.Zero) ? null : new IADLXManualPowerTuning(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXGPUList new_IADLXGPUListP_Ptr() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_IADLXGPUListP_Ptr();
    SWIGTYPE_p_p_adlx__IADLXGPUList ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXGPUList(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXGPUList copy_IADLXGPUListP_Ptr(IADLXGPUList value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_IADLXGPUListP_Ptr(IADLXGPUList.getCPtr(value));
    SWIGTYPE_p_p_adlx__IADLXGPUList ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXGPUList(cPtr, false);
    return ret;
  }

  public static void delete_IADLXGPUListP_Ptr(SWIGTYPE_p_p_adlx__IADLXGPUList obj) {
    ADLXPINVOKE.delete_IADLXGPUListP_Ptr(SWIGTYPE_p_p_adlx__IADLXGPUList.getCPtr(obj));
  }

  public static void IADLXGPUListP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXGPUList obj, IADLXGPUList value) {
    ADLXPINVOKE.IADLXGPUListP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXGPUList.getCPtr(obj), IADLXGPUList.getCPtr(value));
  }

  public static IADLXGPUList IADLXGPUListP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXGPUList obj) {
    global::System.IntPtr cPtr = ADLXPINVOKE.IADLXGPUListP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXGPUList.getCPtr(obj));
    IADLXGPUList ret = (cPtr == global::System.IntPtr.Zero) ? null : new IADLXGPUList(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXGPU new_IADLXGPUP_Ptr() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_IADLXGPUP_Ptr();
    SWIGTYPE_p_p_adlx__IADLXGPU ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXGPU(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXGPU copy_IADLXGPUP_Ptr(IADLXGPU value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_IADLXGPUP_Ptr(IADLXGPU.getCPtr(value));
    SWIGTYPE_p_p_adlx__IADLXGPU ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXGPU(cPtr, false);
    return ret;
  }

  public static void delete_IADLXGPUP_Ptr(SWIGTYPE_p_p_adlx__IADLXGPU obj) {
    ADLXPINVOKE.delete_IADLXGPUP_Ptr(SWIGTYPE_p_p_adlx__IADLXGPU.getCPtr(obj));
  }

  public static void IADLXGPUP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXGPU obj, IADLXGPU value) {
    ADLXPINVOKE.IADLXGPUP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXGPU.getCPtr(obj), IADLXGPU.getCPtr(value));
  }

  public static IADLXGPU IADLXGPUP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXGPU obj) {
    global::System.IntPtr cPtr = ADLXPINVOKE.IADLXGPUP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXGPU.getCPtr(obj));
    IADLXGPU ret = (cPtr == global::System.IntPtr.Zero) ? null : new IADLXGPU(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXGPUAutoTuning new_IADLXGPUAutoTuningP_Ptr() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_IADLXGPUAutoTuningP_Ptr();
    SWIGTYPE_p_p_adlx__IADLXGPUAutoTuning ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXGPUAutoTuning(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXGPUAutoTuning copy_IADLXGPUAutoTuningP_Ptr(IADLXGPUAutoTuning value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_IADLXGPUAutoTuningP_Ptr(IADLXGPUAutoTuning.getCPtr(value));
    SWIGTYPE_p_p_adlx__IADLXGPUAutoTuning ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXGPUAutoTuning(cPtr, false);
    return ret;
  }

  public static void delete_IADLXGPUAutoTuningP_Ptr(SWIGTYPE_p_p_adlx__IADLXGPUAutoTuning obj) {
    ADLXPINVOKE.delete_IADLXGPUAutoTuningP_Ptr(SWIGTYPE_p_p_adlx__IADLXGPUAutoTuning.getCPtr(obj));
  }

  public static void IADLXGPUAutoTuningP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXGPUAutoTuning obj, IADLXGPUAutoTuning value) {
    ADLXPINVOKE.IADLXGPUAutoTuningP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXGPUAutoTuning.getCPtr(obj), IADLXGPUAutoTuning.getCPtr(value));
  }

  public static IADLXGPUAutoTuning IADLXGPUAutoTuningP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXGPUAutoTuning obj) {
    global::System.IntPtr cPtr = ADLXPINVOKE.IADLXGPUAutoTuningP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXGPUAutoTuning.getCPtr(obj));
    IADLXGPUAutoTuning ret = (cPtr == global::System.IntPtr.Zero) ? null : new IADLXGPUAutoTuning(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXInterface new_IADLXInterfaceP_Ptr() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_IADLXInterfaceP_Ptr();
    SWIGTYPE_p_p_adlx__IADLXInterface ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXInterface(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXInterface copy_IADLXInterfaceP_Ptr(IADLXInterface value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_IADLXInterfaceP_Ptr(IADLXInterface.getCPtr(value));
    SWIGTYPE_p_p_adlx__IADLXInterface ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXInterface(cPtr, false);
    return ret;
  }

  public static void delete_IADLXInterfaceP_Ptr(SWIGTYPE_p_p_adlx__IADLXInterface obj) {
    ADLXPINVOKE.delete_IADLXInterfaceP_Ptr(SWIGTYPE_p_p_adlx__IADLXInterface.getCPtr(obj));
  }

  public static void IADLXInterfaceP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXInterface obj, IADLXInterface value) {
    ADLXPINVOKE.IADLXInterfaceP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXInterface.getCPtr(obj), IADLXInterface.getCPtr(value));
  }

  public static IADLXInterface IADLXInterfaceP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXInterface obj) {
    global::System.IntPtr cPtr = ADLXPINVOKE.IADLXInterfaceP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXInterface.getCPtr(obj));
    IADLXInterface ret = (cPtr == global::System.IntPtr.Zero) ? null : new IADLXInterface(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_void new_voidP_Ptr() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_voidP_Ptr();
    SWIGTYPE_p_p_void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_void(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_void copy_voidP_Ptr(SWIGTYPE_p_void value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_voidP_Ptr(SWIGTYPE_p_void.getCPtr(value));
    SWIGTYPE_p_p_void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_void(cPtr, false);
    return ret;
  }

  public static void delete_voidP_Ptr(SWIGTYPE_p_p_void obj) {
    ADLXPINVOKE.delete_voidP_Ptr(SWIGTYPE_p_p_void.getCPtr(obj));
  }

  public static void voidP_Ptr_assign(SWIGTYPE_p_p_void obj, SWIGTYPE_p_void value) {
    ADLXPINVOKE.voidP_Ptr_assign(SWIGTYPE_p_p_void.getCPtr(obj), SWIGTYPE_p_void.getCPtr(value));
  }

  public static SWIGTYPE_p_void voidP_Ptr_value(SWIGTYPE_p_p_void obj) {
    global::System.IntPtr cPtr = ADLXPINVOKE.voidP_Ptr_value(SWIGTYPE_p_p_void.getCPtr(obj));
    SWIGTYPE_p_void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_char new_charP_Ptr() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_charP_Ptr();
    SWIGTYPE_p_p_char ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_char(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_char copy_charP_Ptr(string value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_charP_Ptr(value);
    SWIGTYPE_p_p_char ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_char(cPtr, false);
    return ret;
  }

  public static void delete_charP_Ptr(SWIGTYPE_p_p_char obj) {
    ADLXPINVOKE.delete_charP_Ptr(SWIGTYPE_p_p_char.getCPtr(obj));
  }

  public static void charP_Ptr_assign(SWIGTYPE_p_p_char obj, string value) {
    ADLXPINVOKE.charP_Ptr_assign(SWIGTYPE_p_p_char.getCPtr(obj), value);
  }

  public static string charP_Ptr_value(SWIGTYPE_p_p_char obj) {
    string ret = ADLXPINVOKE.charP_Ptr_value(SWIGTYPE_p_p_char.getCPtr(obj));
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXManualFanTuningState new_manualFanTuningStateP_Ptr() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_manualFanTuningStateP_Ptr();
    SWIGTYPE_p_p_adlx__IADLXManualFanTuningState ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXManualFanTuningState(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXManualFanTuningState copy_manualFanTuningStateP_Ptr(IADLXManualFanTuningState value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_manualFanTuningStateP_Ptr(IADLXManualFanTuningState.getCPtr(value));
    SWIGTYPE_p_p_adlx__IADLXManualFanTuningState ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXManualFanTuningState(cPtr, false);
    return ret;
  }

  public static void delete_manualFanTuningStateP_Ptr(SWIGTYPE_p_p_adlx__IADLXManualFanTuningState obj) {
    ADLXPINVOKE.delete_manualFanTuningStateP_Ptr(SWIGTYPE_p_p_adlx__IADLXManualFanTuningState.getCPtr(obj));
  }

  public static void manualFanTuningStateP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXManualFanTuningState obj, IADLXManualFanTuningState value) {
    ADLXPINVOKE.manualFanTuningStateP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXManualFanTuningState.getCPtr(obj), IADLXManualFanTuningState.getCPtr(value));
  }

  public static IADLXManualFanTuningState manualFanTuningStateP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXManualFanTuningState obj) {
    global::System.IntPtr cPtr = ADLXPINVOKE.manualFanTuningStateP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXManualFanTuningState.getCPtr(obj));
    IADLXManualFanTuningState ret = (cPtr == global::System.IntPtr.Zero) ? null : new IADLXManualFanTuningState(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXManualFanTuningStateList new_manualFanTuningStateListP_Ptr() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_manualFanTuningStateListP_Ptr();
    SWIGTYPE_p_p_adlx__IADLXManualFanTuningStateList ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXManualFanTuningStateList(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXManualFanTuningStateList copy_manualFanTuningStateListP_Ptr(IADLXManualFanTuningStateList value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_manualFanTuningStateListP_Ptr(IADLXManualFanTuningStateList.getCPtr(value));
    SWIGTYPE_p_p_adlx__IADLXManualFanTuningStateList ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXManualFanTuningStateList(cPtr, false);
    return ret;
  }

  public static void delete_manualFanTuningStateListP_Ptr(SWIGTYPE_p_p_adlx__IADLXManualFanTuningStateList obj) {
    ADLXPINVOKE.delete_manualFanTuningStateListP_Ptr(SWIGTYPE_p_p_adlx__IADLXManualFanTuningStateList.getCPtr(obj));
  }

  public static void manualFanTuningStateListP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXManualFanTuningStateList obj, IADLXManualFanTuningStateList value) {
    ADLXPINVOKE.manualFanTuningStateListP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXManualFanTuningStateList.getCPtr(obj), IADLXManualFanTuningStateList.getCPtr(value));
  }

  public static IADLXManualFanTuningStateList manualFanTuningStateListP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXManualFanTuningStateList obj) {
    global::System.IntPtr cPtr = ADLXPINVOKE.manualFanTuningStateListP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXManualFanTuningStateList.getCPtr(obj));
    IADLXManualFanTuningStateList ret = (cPtr == global::System.IntPtr.Zero) ? null : new IADLXManualFanTuningStateList(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXManualTuningState new_manualTuningStateP_Ptr() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_manualTuningStateP_Ptr();
    SWIGTYPE_p_p_adlx__IADLXManualTuningState ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXManualTuningState(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXManualTuningState copy_manualTuningStateP_Ptr(IADLXManualTuningState value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_manualTuningStateP_Ptr(IADLXManualTuningState.getCPtr(value));
    SWIGTYPE_p_p_adlx__IADLXManualTuningState ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXManualTuningState(cPtr, false);
    return ret;
  }

  public static void delete_manualTuningStateP_Ptr(SWIGTYPE_p_p_adlx__IADLXManualTuningState obj) {
    ADLXPINVOKE.delete_manualTuningStateP_Ptr(SWIGTYPE_p_p_adlx__IADLXManualTuningState.getCPtr(obj));
  }

  public static void manualTuningStateP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXManualTuningState obj, IADLXManualTuningState value) {
    ADLXPINVOKE.manualTuningStateP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXManualTuningState.getCPtr(obj), IADLXManualTuningState.getCPtr(value));
  }

  public static IADLXManualTuningState manualTuningStateP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXManualTuningState obj) {
    global::System.IntPtr cPtr = ADLXPINVOKE.manualTuningStateP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXManualTuningState.getCPtr(obj));
    IADLXManualTuningState ret = (cPtr == global::System.IntPtr.Zero) ? null : new IADLXManualTuningState(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXManualTuningStateList new_manualTuningStateListP_Ptr() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_manualTuningStateListP_Ptr();
    SWIGTYPE_p_p_adlx__IADLXManualTuningStateList ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXManualTuningStateList(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXManualTuningStateList copy_manualTuningStateListP_Ptr(IADLXManualTuningStateList value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_manualTuningStateListP_Ptr(IADLXManualTuningStateList.getCPtr(value));
    SWIGTYPE_p_p_adlx__IADLXManualTuningStateList ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXManualTuningStateList(cPtr, false);
    return ret;
  }

  public static void delete_manualTuningStateListP_Ptr(SWIGTYPE_p_p_adlx__IADLXManualTuningStateList obj) {
    ADLXPINVOKE.delete_manualTuningStateListP_Ptr(SWIGTYPE_p_p_adlx__IADLXManualTuningStateList.getCPtr(obj));
  }

  public static void manualTuningStateListP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXManualTuningStateList obj, IADLXManualTuningStateList value) {
    ADLXPINVOKE.manualTuningStateListP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXManualTuningStateList.getCPtr(obj), IADLXManualTuningStateList.getCPtr(value));
  }

  public static IADLXManualTuningStateList manualTuningStateListP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXManualTuningStateList obj) {
    global::System.IntPtr cPtr = ADLXPINVOKE.manualTuningStateListP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXManualTuningStateList.getCPtr(obj));
    IADLXManualTuningStateList ret = (cPtr == global::System.IntPtr.Zero) ? null : new IADLXManualTuningStateList(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXMemoryTimingDescription new_memoryTimingDescriptionP_Ptr() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_memoryTimingDescriptionP_Ptr();
    SWIGTYPE_p_p_adlx__IADLXMemoryTimingDescription ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXMemoryTimingDescription(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXMemoryTimingDescription copy_memoryTimingDescriptionP_Ptr(IADLXMemoryTimingDescription value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_memoryTimingDescriptionP_Ptr(IADLXMemoryTimingDescription.getCPtr(value));
    SWIGTYPE_p_p_adlx__IADLXMemoryTimingDescription ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXMemoryTimingDescription(cPtr, false);
    return ret;
  }

  public static void delete_memoryTimingDescriptionP_Ptr(SWIGTYPE_p_p_adlx__IADLXMemoryTimingDescription obj) {
    ADLXPINVOKE.delete_memoryTimingDescriptionP_Ptr(SWIGTYPE_p_p_adlx__IADLXMemoryTimingDescription.getCPtr(obj));
  }

  public static void memoryTimingDescriptionP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXMemoryTimingDescription obj, IADLXMemoryTimingDescription value) {
    ADLXPINVOKE.memoryTimingDescriptionP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXMemoryTimingDescription.getCPtr(obj), IADLXMemoryTimingDescription.getCPtr(value));
  }

  public static IADLXMemoryTimingDescription memoryTimingDescriptionP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXMemoryTimingDescription obj) {
    global::System.IntPtr cPtr = ADLXPINVOKE.memoryTimingDescriptionP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXMemoryTimingDescription.getCPtr(obj));
    IADLXMemoryTimingDescription ret = (cPtr == global::System.IntPtr.Zero) ? null : new IADLXMemoryTimingDescription(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXMemoryTimingDescriptionList new_memoryTimingDescriptionListP_Ptr() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_memoryTimingDescriptionListP_Ptr();
    SWIGTYPE_p_p_adlx__IADLXMemoryTimingDescriptionList ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXMemoryTimingDescriptionList(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXMemoryTimingDescriptionList copy_memoryTimingDescriptionListP_Ptr(IADLXMemoryTimingDescriptionList value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_memoryTimingDescriptionListP_Ptr(IADLXMemoryTimingDescriptionList.getCPtr(value));
    SWIGTYPE_p_p_adlx__IADLXMemoryTimingDescriptionList ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXMemoryTimingDescriptionList(cPtr, false);
    return ret;
  }

  public static void delete_memoryTimingDescriptionListP_Ptr(SWIGTYPE_p_p_adlx__IADLXMemoryTimingDescriptionList obj) {
    ADLXPINVOKE.delete_memoryTimingDescriptionListP_Ptr(SWIGTYPE_p_p_adlx__IADLXMemoryTimingDescriptionList.getCPtr(obj));
  }

  public static void memoryTimingDescriptionListP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXMemoryTimingDescriptionList obj, IADLXMemoryTimingDescriptionList value) {
    ADLXPINVOKE.memoryTimingDescriptionListP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXMemoryTimingDescriptionList.getCPtr(obj), IADLXMemoryTimingDescriptionList.getCPtr(value));
  }

  public static IADLXMemoryTimingDescriptionList memoryTimingDescriptionListP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXMemoryTimingDescriptionList obj) {
    global::System.IntPtr cPtr = ADLXPINVOKE.memoryTimingDescriptionListP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXMemoryTimingDescriptionList.getCPtr(obj));
    IADLXMemoryTimingDescriptionList ret = (cPtr == global::System.IntPtr.Zero) ? null : new IADLXMemoryTimingDescriptionList(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXGPUMetrics new_gpuMetricsP_Ptr() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_gpuMetricsP_Ptr();
    SWIGTYPE_p_p_adlx__IADLXGPUMetrics ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXGPUMetrics(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXGPUMetrics copy_gpuMetricsP_Ptr(IADLXGPUMetrics value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_gpuMetricsP_Ptr(IADLXGPUMetrics.getCPtr(value));
    SWIGTYPE_p_p_adlx__IADLXGPUMetrics ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXGPUMetrics(cPtr, false);
    return ret;
  }

  public static void delete_gpuMetricsP_Ptr(SWIGTYPE_p_p_adlx__IADLXGPUMetrics obj) {
    ADLXPINVOKE.delete_gpuMetricsP_Ptr(SWIGTYPE_p_p_adlx__IADLXGPUMetrics.getCPtr(obj));
  }

  public static void gpuMetricsP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXGPUMetrics obj, IADLXGPUMetrics value) {
    ADLXPINVOKE.gpuMetricsP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXGPUMetrics.getCPtr(obj), IADLXGPUMetrics.getCPtr(value));
  }

  public static IADLXGPUMetrics gpuMetricsP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXGPUMetrics obj) {
    global::System.IntPtr cPtr = ADLXPINVOKE.gpuMetricsP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXGPUMetrics.getCPtr(obj));
    IADLXGPUMetrics ret = (cPtr == global::System.IntPtr.Zero) ? null : new IADLXGPUMetrics(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXGPUMetrics1 new_gpuMetrics1P_Ptr() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_gpuMetrics1P_Ptr();
    SWIGTYPE_p_p_adlx__IADLXGPUMetrics1 ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXGPUMetrics1(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXGPUMetrics1 copy_gpuMetrics1P_Ptr(IADLXGPUMetrics1 value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_gpuMetrics1P_Ptr(IADLXGPUMetrics1.getCPtr(value));
    SWIGTYPE_p_p_adlx__IADLXGPUMetrics1 ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXGPUMetrics1(cPtr, false);
    return ret;
  }

  public static void delete_gpuMetrics1P_Ptr(SWIGTYPE_p_p_adlx__IADLXGPUMetrics1 obj) {
    ADLXPINVOKE.delete_gpuMetrics1P_Ptr(SWIGTYPE_p_p_adlx__IADLXGPUMetrics1.getCPtr(obj));
  }

  public static void gpuMetrics1P_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXGPUMetrics1 obj, IADLXGPUMetrics1 value) {
    ADLXPINVOKE.gpuMetrics1P_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXGPUMetrics1.getCPtr(obj), IADLXGPUMetrics1.getCPtr(value));
  }

  public static IADLXGPUMetrics1 gpuMetrics1P_Ptr_value(SWIGTYPE_p_p_adlx__IADLXGPUMetrics1 obj) {
    global::System.IntPtr cPtr = ADLXPINVOKE.gpuMetrics1P_Ptr_value(SWIGTYPE_p_p_adlx__IADLXGPUMetrics1.getCPtr(obj));
    IADLXGPUMetrics1 ret = (cPtr == global::System.IntPtr.Zero) ? null : new IADLXGPUMetrics1(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXGPUMetricsSupport new_gpuMetricsSupportP_Ptr() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_gpuMetricsSupportP_Ptr();
    SWIGTYPE_p_p_adlx__IADLXGPUMetricsSupport ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXGPUMetricsSupport(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXGPUMetricsSupport copy_gpuMetricsSupportP_Ptr(IADLXGPUMetricsSupport value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_gpuMetricsSupportP_Ptr(IADLXGPUMetricsSupport.getCPtr(value));
    SWIGTYPE_p_p_adlx__IADLXGPUMetricsSupport ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXGPUMetricsSupport(cPtr, false);
    return ret;
  }

  public static void delete_gpuMetricsSupportP_Ptr(SWIGTYPE_p_p_adlx__IADLXGPUMetricsSupport obj) {
    ADLXPINVOKE.delete_gpuMetricsSupportP_Ptr(SWIGTYPE_p_p_adlx__IADLXGPUMetricsSupport.getCPtr(obj));
  }

  public static void gpuMetricsSupportP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXGPUMetricsSupport obj, IADLXGPUMetricsSupport value) {
    ADLXPINVOKE.gpuMetricsSupportP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXGPUMetricsSupport.getCPtr(obj), IADLXGPUMetricsSupport.getCPtr(value));
  }

  public static IADLXGPUMetricsSupport gpuMetricsSupportP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXGPUMetricsSupport obj) {
    global::System.IntPtr cPtr = ADLXPINVOKE.gpuMetricsSupportP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXGPUMetricsSupport.getCPtr(obj));
    IADLXGPUMetricsSupport ret = (cPtr == global::System.IntPtr.Zero) ? null : new IADLXGPUMetricsSupport(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXGPUMetricsSupport1 new_gpuMetricsSupport1P_Ptr() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_gpuMetricsSupport1P_Ptr();
    SWIGTYPE_p_p_adlx__IADLXGPUMetricsSupport1 ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXGPUMetricsSupport1(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXGPUMetricsSupport1 copy_gpuMetricsSupport1P_Ptr(IADLXGPUMetricsSupport1 value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_gpuMetricsSupport1P_Ptr(IADLXGPUMetricsSupport1.getCPtr(value));
    SWIGTYPE_p_p_adlx__IADLXGPUMetricsSupport1 ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXGPUMetricsSupport1(cPtr, false);
    return ret;
  }

  public static void delete_gpuMetricsSupport1P_Ptr(SWIGTYPE_p_p_adlx__IADLXGPUMetricsSupport1 obj) {
    ADLXPINVOKE.delete_gpuMetricsSupport1P_Ptr(SWIGTYPE_p_p_adlx__IADLXGPUMetricsSupport1.getCPtr(obj));
  }

  public static void gpuMetricsSupport1P_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXGPUMetricsSupport1 obj, IADLXGPUMetricsSupport1 value) {
    ADLXPINVOKE.gpuMetricsSupport1P_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXGPUMetricsSupport1.getCPtr(obj), IADLXGPUMetricsSupport1.getCPtr(value));
  }

  public static IADLXGPUMetricsSupport1 gpuMetricsSupport1P_Ptr_value(SWIGTYPE_p_p_adlx__IADLXGPUMetricsSupport1 obj) {
    global::System.IntPtr cPtr = ADLXPINVOKE.gpuMetricsSupport1P_Ptr_value(SWIGTYPE_p_p_adlx__IADLXGPUMetricsSupport1.getCPtr(obj));
    IADLXGPUMetricsSupport1 ret = (cPtr == global::System.IntPtr.Zero) ? null : new IADLXGPUMetricsSupport1(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXPerformanceMonitoringServices new_performanceMonitoringServicesP_Ptr() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_performanceMonitoringServicesP_Ptr();
    SWIGTYPE_p_p_adlx__IADLXPerformanceMonitoringServices ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXPerformanceMonitoringServices(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXPerformanceMonitoringServices copy_performanceMonitoringServicesP_Ptr(IADLXPerformanceMonitoringServices value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_performanceMonitoringServicesP_Ptr(IADLXPerformanceMonitoringServices.getCPtr(value));
    SWIGTYPE_p_p_adlx__IADLXPerformanceMonitoringServices ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXPerformanceMonitoringServices(cPtr, false);
    return ret;
  }

  public static void delete_performanceMonitoringServicesP_Ptr(SWIGTYPE_p_p_adlx__IADLXPerformanceMonitoringServices obj) {
    ADLXPINVOKE.delete_performanceMonitoringServicesP_Ptr(SWIGTYPE_p_p_adlx__IADLXPerformanceMonitoringServices.getCPtr(obj));
  }

  public static void performanceMonitoringServicesP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXPerformanceMonitoringServices obj, IADLXPerformanceMonitoringServices value) {
    ADLXPINVOKE.performanceMonitoringServicesP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXPerformanceMonitoringServices.getCPtr(obj), IADLXPerformanceMonitoringServices.getCPtr(value));
  }

  public static IADLXPerformanceMonitoringServices performanceMonitoringServicesP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXPerformanceMonitoringServices obj) {
    global::System.IntPtr cPtr = ADLXPINVOKE.performanceMonitoringServicesP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXPerformanceMonitoringServices.getCPtr(obj));
    IADLXPerformanceMonitoringServices ret = (cPtr == global::System.IntPtr.Zero) ? null : new IADLXPerformanceMonitoringServices(cPtr, false);
    return ret;
  }

  public static readonly int MAX_USER_3DLUT_NUM_POINTS = ADLXPINVOKE.MAX_USER_3DLUT_NUM_POINTS_get();
}
