//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class IADLXGPUMetricsSupport : IADLXInterface {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal IADLXGPUMetricsSupport(global::System.IntPtr cPtr, bool cMemoryOwn) : base(ADLXPINVOKE.IADLXGPUMetricsSupport_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IADLXGPUMetricsSupport obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(IADLXGPUMetricsSupport obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ADLXPINVOKE.delete_IADLXGPUMetricsSupport(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public new static SWIGTYPE_p_wchar_t IID() {
    global::System.IntPtr cPtr = ADLXPINVOKE.IADLXGPUMetricsSupport_IID();
    SWIGTYPE_p_wchar_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_wchar_t(cPtr, false);
    return ret;
  }

  public virtual ADLX_RESULT IsSupportedGPUUsage(out bool supported) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPUMetricsSupport_IsSupportedGPUUsage(swigCPtr, out supported);
    return ret;
  }

  public virtual ADLX_RESULT IsSupportedGPUClockSpeed(out bool supported) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPUMetricsSupport_IsSupportedGPUClockSpeed(swigCPtr, out supported);
    return ret;
  }

  public virtual ADLX_RESULT IsSupportedGPUVRAMClockSpeed(out bool supported) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPUMetricsSupport_IsSupportedGPUVRAMClockSpeed(swigCPtr, out supported);
    return ret;
  }

  public virtual ADLX_RESULT IsSupportedGPUTemperature(out bool supported) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPUMetricsSupport_IsSupportedGPUTemperature(swigCPtr, out supported);
    return ret;
  }

  public virtual ADLX_RESULT IsSupportedGPUHotspotTemperature(out bool supported) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPUMetricsSupport_IsSupportedGPUHotspotTemperature(swigCPtr, out supported);
    return ret;
  }

  public virtual ADLX_RESULT IsSupportedGPUPower(out bool supported) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPUMetricsSupport_IsSupportedGPUPower(swigCPtr, out supported);
    return ret;
  }

  public virtual ADLX_RESULT IsSupportedGPUTotalBoardPower(out bool supported) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPUMetricsSupport_IsSupportedGPUTotalBoardPower(swigCPtr, out supported);
    return ret;
  }

  public virtual ADLX_RESULT IsSupportedGPUFanSpeed(out bool supported) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPUMetricsSupport_IsSupportedGPUFanSpeed(swigCPtr, out supported);
    return ret;
  }

  public virtual ADLX_RESULT IsSupportedGPUVRAM(out bool supported) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPUMetricsSupport_IsSupportedGPUVRAM(swigCPtr, out supported);
    return ret;
  }

  public virtual ADLX_RESULT IsSupportedGPUVoltage(out bool supported) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPUMetricsSupport_IsSupportedGPUVoltage(swigCPtr, out supported);
    return ret;
  }

  public virtual ADLX_RESULT GetGPUUsageRange(out int minValue, out int maxValue) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPUMetricsSupport_GetGPUUsageRange(swigCPtr, out minValue, out maxValue);
    return ret;
  }

  public virtual ADLX_RESULT GetGPUClockSpeedRange(out int minValue, out int maxValue) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPUMetricsSupport_GetGPUClockSpeedRange(swigCPtr, out minValue, out maxValue);
    return ret;
  }

  public virtual ADLX_RESULT GetGPUVRAMClockSpeedRange(out int minValue, out int maxValue) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPUMetricsSupport_GetGPUVRAMClockSpeedRange(swigCPtr, out minValue, out maxValue);
    return ret;
  }

  public virtual ADLX_RESULT GetGPUTemperatureRange(out int minValue, out int maxValue) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPUMetricsSupport_GetGPUTemperatureRange(swigCPtr, out minValue, out maxValue);
    return ret;
  }

  public virtual ADLX_RESULT GetGPUHotspotTemperatureRange(out int minValue, out int maxValue) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPUMetricsSupport_GetGPUHotspotTemperatureRange(swigCPtr, out minValue, out maxValue);
    return ret;
  }

  public virtual ADLX_RESULT GetGPUPowerRange(out int minValue, out int maxValue) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPUMetricsSupport_GetGPUPowerRange(swigCPtr, out minValue, out maxValue);
    return ret;
  }

  public virtual ADLX_RESULT GetGPUFanSpeedRange(out int minValue, out int maxValue) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPUMetricsSupport_GetGPUFanSpeedRange(swigCPtr, out minValue, out maxValue);
    return ret;
  }

  public virtual ADLX_RESULT GetGPUVRAMRange(out int minValue, out int maxValue) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPUMetricsSupport_GetGPUVRAMRange(swigCPtr, out minValue, out maxValue);
    return ret;
  }

  public virtual ADLX_RESULT GetGPUVoltageRange(out int minValue, out int maxValue) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPUMetricsSupport_GetGPUVoltageRange(swigCPtr, out minValue, out maxValue);
    return ret;
  }

  public virtual ADLX_RESULT GetGPUTotalBoardPowerRange(out int minValue, out int maxValue) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPUMetricsSupport_GetGPUTotalBoardPowerRange(swigCPtr, out minValue, out maxValue);
    return ret;
  }

  public virtual ADLX_RESULT GetGPUIntakeTemperatureRange(out int minValue, out int maxValue) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPUMetricsSupport_GetGPUIntakeTemperatureRange(swigCPtr, out minValue, out maxValue);
    return ret;
  }

  public virtual ADLX_RESULT IsSupportedGPUIntakeTemperature(out bool supported) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPUMetricsSupport_IsSupportedGPUIntakeTemperature(swigCPtr, out supported);
    return ret;
  }

}
