//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class IADLXGPUAutoTuningCompleteListener : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal IADLXGPUAutoTuningCompleteListener(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IADLXGPUAutoTuningCompleteListener obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(IADLXGPUAutoTuningCompleteListener obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~IADLXGPUAutoTuningCompleteListener() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ADLXPINVOKE.delete_IADLXGPUAutoTuningCompleteListener(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public virtual bool OnGPUAutoTuningComplete(IADLXGPUAutoTuningCompleteEvent pGPUAutoTuningCompleteEvent) {
    bool ret = ADLXPINVOKE.IADLXGPUAutoTuningCompleteListener_OnGPUAutoTuningComplete(swigCPtr, IADLXGPUAutoTuningCompleteEvent.getCPtr(pGPUAutoTuningCompleteEvent));
    return ret;
  }

  public IADLXGPUAutoTuningCompleteListener() : this(ADLXPINVOKE.new_IADLXGPUAutoTuningCompleteListener(), true) {
    SwigDirectorConnect();
  }

  private void SwigDirectorConnect() {
    if (SwigDerivedClassHasMethod("OnGPUAutoTuningComplete", swigMethodTypes0))
      swigDelegate0 = new SwigDelegateIADLXGPUAutoTuningCompleteListener_0(SwigDirectorMethodOnGPUAutoTuningComplete);
    ADLXPINVOKE.IADLXGPUAutoTuningCompleteListener_director_connect(swigCPtr, swigDelegate0);
  }

  private bool SwigDerivedClassHasMethod(string methodName, global::System.Type[] methodTypes) {
    global::System.Reflection.MethodInfo[] methodInfos = this.GetType().GetMethods(
        global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance);
    foreach (global::System.Reflection.MethodInfo methodInfo in methodInfos) {
      if (methodInfo.DeclaringType == null)
        continue;

      if (methodInfo.Name != methodName)
        continue;

      var parameters = methodInfo.GetParameters();
      if (parameters.Length != methodTypes.Length)
        continue;

      bool parametersMatch = true;
      for (var i = 0; i < parameters.Length; i++) {
        if (parameters[i].ParameterType != methodTypes[i]) {
          parametersMatch = false;
          break;
        }
      }

      if (!parametersMatch)
        continue;

      if (methodInfo.IsVirtual && (methodInfo.DeclaringType.IsSubclassOf(typeof(IADLXGPUAutoTuningCompleteListener))) &&
        methodInfo.DeclaringType != methodInfo.GetBaseDefinition().DeclaringType) {
        return true;
      }
    }

    return false;
  }

  private bool SwigDirectorMethodOnGPUAutoTuningComplete(global::System.IntPtr pGPUAutoTuningCompleteEvent) {
    return OnGPUAutoTuningComplete((pGPUAutoTuningCompleteEvent == global::System.IntPtr.Zero) ? null : new IADLXGPUAutoTuningCompleteEvent(pGPUAutoTuningCompleteEvent, false));
  }

  public delegate bool SwigDelegateIADLXGPUAutoTuningCompleteListener_0(global::System.IntPtr pGPUAutoTuningCompleteEvent);

  private SwigDelegateIADLXGPUAutoTuningCompleteListener_0 swigDelegate0;

  private static global::System.Type[] swigMethodTypes0 = new global::System.Type[] { typeof(IADLXGPUAutoTuningCompleteEvent) };
}
