//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class IADLXGPU : IADLXInterface {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal IADLXGPU(global::System.IntPtr cPtr, bool cMemoryOwn) : base(ADLXPINVOKE.IADLXGPU_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IADLXGPU obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(IADLXGPU obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ADLXPINVOKE.delete_IADLXGPU(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public new static SWIGTYPE_p_wchar_t IID() {
    global::System.IntPtr cPtr = ADLXPINVOKE.IADLXGPU_IID();
    SWIGTYPE_p_wchar_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_wchar_t(cPtr, false);
    return ret;
  }

  public virtual ADLX_RESULT VendorId(out string vendorId) {
global::System.IntPtr tmpvendorId=global::System.IntPtr.Zero;
    try {
      ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPU_VendorId(swigCPtr, ref tmpvendorId);
      return ret;
    } finally {
vendorId=global::System.Runtime.InteropServices.Marshal.PtrToStringAnsi(tmpvendorId);
    }
  }

  public virtual ADLX_RESULT ASICFamilyType(SWIGTYPE_p_ADLX_ASIC_FAMILY_TYPE asicFamilyType) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPU_ASICFamilyType(swigCPtr, SWIGTYPE_p_ADLX_ASIC_FAMILY_TYPE.getCPtr(asicFamilyType));
    return ret;
  }

  public virtual ADLX_RESULT Type(SWIGTYPE_p_ADLX_GPU_TYPE gpuType) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPU_Type(swigCPtr, SWIGTYPE_p_ADLX_GPU_TYPE.getCPtr(gpuType));
    return ret;
  }

  public virtual ADLX_RESULT IsExternal(out bool isExternal) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPU_IsExternal(swigCPtr, out isExternal);
    return ret;
  }

  public virtual ADLX_RESULT Name(out string name) {
global::System.IntPtr tmpname=global::System.IntPtr.Zero;
    try {
      ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPU_Name(swigCPtr, ref tmpname);
      return ret;
    } finally {
name=global::System.Runtime.InteropServices.Marshal.PtrToStringAnsi(tmpname);
    }
  }

  public virtual ADLX_RESULT DriverPath(out string driverPath) {
global::System.IntPtr tmpdriverPath=global::System.IntPtr.Zero;
    try {
      ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPU_DriverPath(swigCPtr, ref tmpdriverPath);
      return ret;
    } finally {
driverPath=global::System.Runtime.InteropServices.Marshal.PtrToStringAnsi(tmpdriverPath);
    }
  }

  public virtual ADLX_RESULT PNPString(out string pnpString) {
global::System.IntPtr tmppnpString=global::System.IntPtr.Zero;
    try {
      ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPU_PNPString(swigCPtr, ref tmppnpString);
      return ret;
    } finally {
pnpString=global::System.Runtime.InteropServices.Marshal.PtrToStringAnsi(tmppnpString);
    }
  }

  public virtual ADLX_RESULT HasDesktops(out bool hasDesktops) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPU_HasDesktops(swigCPtr, out hasDesktops);
    return ret;
  }

  public virtual ADLX_RESULT TotalVRAM(out uint vramMB) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPU_TotalVRAM(swigCPtr, out vramMB);
    return ret;
  }

  public virtual ADLX_RESULT VRAMType(out string type) {
global::System.IntPtr tmptype=global::System.IntPtr.Zero;
    try {
      ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPU_VRAMType(swigCPtr, ref tmptype);
      return ret;
    } finally {
type=global::System.Runtime.InteropServices.Marshal.PtrToStringAnsi(tmptype);
    }
  }

  public virtual ADLX_RESULT BIOSInfo(out string partNumber, out string version, out string date) {
global::System.IntPtr tmppartNumber=global::System.IntPtr.Zero;
global::System.IntPtr tmpversion=global::System.IntPtr.Zero;
global::System.IntPtr tmpdate=global::System.IntPtr.Zero;
    try {
      ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPU_BIOSInfo(swigCPtr, ref tmppartNumber, ref tmpversion, ref tmpdate);
      return ret;
    } finally {
partNumber=global::System.Runtime.InteropServices.Marshal.PtrToStringAnsi(tmppartNumber);
version=global::System.Runtime.InteropServices.Marshal.PtrToStringAnsi(tmpversion);
date=global::System.Runtime.InteropServices.Marshal.PtrToStringAnsi(tmpdate);
    }
  }

  public virtual ADLX_RESULT DeviceId(out string deviceId) {
global::System.IntPtr tmpdeviceId=global::System.IntPtr.Zero;
    try {
      ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPU_DeviceId(swigCPtr, ref tmpdeviceId);
      return ret;
    } finally {
deviceId=global::System.Runtime.InteropServices.Marshal.PtrToStringAnsi(tmpdeviceId);
    }
  }

  public virtual ADLX_RESULT RevisionId(out string revisionId) {
global::System.IntPtr tmprevisionId=global::System.IntPtr.Zero;
    try {
      ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPU_RevisionId(swigCPtr, ref tmprevisionId);
      return ret;
    } finally {
revisionId=global::System.Runtime.InteropServices.Marshal.PtrToStringAnsi(tmprevisionId);
    }
  }

  public virtual ADLX_RESULT SubSystemId(out string subSystemId) {
global::System.IntPtr tmpsubSystemId=global::System.IntPtr.Zero;
    try {
      ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPU_SubSystemId(swigCPtr, ref tmpsubSystemId);
      return ret;
    } finally {
subSystemId=global::System.Runtime.InteropServices.Marshal.PtrToStringAnsi(tmpsubSystemId);
    }
  }

  public virtual ADLX_RESULT SubSystemVendorId(out string subSystemVendorId) {
global::System.IntPtr tmpsubSystemVendorId=global::System.IntPtr.Zero;
    try {
      ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPU_SubSystemVendorId(swigCPtr, ref tmpsubSystemVendorId);
      return ret;
    } finally {
subSystemVendorId=global::System.Runtime.InteropServices.Marshal.PtrToStringAnsi(tmpsubSystemVendorId);
    }
  }

  public virtual ADLX_RESULT UniqueId(out int uniqueId) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPU_UniqueId(swigCPtr, out uniqueId);
    return ret;
  }

}
